export enum AuthGrantTypeEnum {
    AUTHORIZATION_CODE = "AUTHORIZATION_CODE",
    CLIENT_CREDENTIALS = "CLIENT_CREDENTIALS",
    RESOURCE_OWNER_PASSWORD_CREDENTIALS = "PASSWORD",
    REFRESH_TOKEN = "REFRESH_TOKEN",
}

