export { AuthorityPageInterface } from './authority-page.interface'
export { AuthorityRegisterInterface } from './authority-register.interface'
export { AuthoritySettingsInterface } from './authority-settings.interface'
export { AuthoritySettingsUpdateInterface } from './authority-settings.interface'
export { AuthorityUsageByUsersInterface } from './authority-usage-by-users.interface'